/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2")
    }
    maven {
        url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots")
    }
    maven {
        url = uri("https://maven.pkg.github.com/wadoon/jmlparser")
        credentials {
            username = project.findProperty("gpr.user") as String? ?: System.getenv("USER")
            password = project.findProperty("gpr.key") as String? ?: System.getenv("TOKEN")
        }
    }
}

dependencies {
    api(libs.org.antlr.antlr4.runtime)
    api(libs.com.github.javaparser.javaparser.symbol.solver.core)
    implementation("io.github.jmltoolkit:jmlparser-symbol-solver-core:3.25.8-SNAPSHOT")
    implementation("io.github.jmltoolkit:jmlparser-core:3.25.8-SNAPSHOT")

}

group = "SmartJML"
version = "1.0-SNAPSHOT"
description = "SmartJML"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
